# Generated by Django 4.2.1 on 2023-06-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_mecanico_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='mantencion')),
                ('mecani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.mecanico')),
            ],
        ),
    ]
