# Generated by Django 4.2.2 on 2023-07-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_trabajo_rename_tipo_contacto_contacto_tipos_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='mecani',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.mecanico'),
        ),
        migrations.AlterField(
            model_name='rechazo',
            name='mecani',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.mecanico'),
        ),
    ]
