# Generated by Django 4.2.2 on 2023-07-13 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0006_mantencion_mensaje_alter_mantencion_mecani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipos_contacto',
            field=models.IntegerField(choices=[[0, 'Sugerencia'], [1, 'Reclamo']], default=0),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='especialista',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rechazo',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rechazo',
            name='tipo_rechazo',
            field=models.IntegerField(choices=[[0, 'Mala Redaccion'], [1, 'Faltas de Ortografia'], [2, 'Imagen Baja Calidad']], default=0),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
